//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.HouseRequirements
{
	/// <summary>
	/// Returns detailed information for a specified House requirement.
	/// </summary>
	public class HouseRequirementDetailRequest : JsonFormatApiRequest<HouseRequirementDetail.HouseRequirementDetailResponse>
	{
		/// <summary>
		/// The requirement's assigned number. For example, the value can be 8070.
		/// </summary>
		public int RequirementNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/house-requirement/{0}", RequirementNumber);
	}
}
