//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.HouseRequirements
{
	/// <summary>
	/// Returns a list of matching communications to a House requirement.
	/// </summary>
	public class HouseRequirementCommunicationListRequest : PagedApiRequest<HouseRequirementCommunicationList.HouseRequirementCommunicationListResponse>
	{
		/// <summary>
		/// The requirement's assigned number. For example, the value can be 8070.
		/// </summary>
		public int RequirementNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/house-requirement/{0}/matching-communications", RequirementNumber);
	}
}
