//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CongressionalRecords
{
	/// <summary>
	/// Returns a list of congressional record issues sorted by most recent.
	/// </summary>
	public class CongressionalRecordListRequest : PagedApiRequest<CongressionalRecordList.CongressionalRecordListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/congressional-record");
	}
}
