//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Amendments
{
	/// <summary>
	/// Returns a list of amendments filtered by the specified congress and amendment type, sorted by date of latest action.
	/// </summary>
	public class AmendmentListRequest : DateRangeApiRequest<AmendmentList.AmendmentListResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of amendment. Value can be hamdt, samdt, or suamdt.
		/// </summary>
		public string AmendmentType { get; set; }

		public override CongressApiEndpoint Endpoint => new("/amendment/{0}/{1}", Congress, AmendmentType);
	}
}
