//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Congresses
{
	/// <summary>
	/// Returns detailed information for the current congress.
	/// </summary>
	public class CongressCurrentListRequest : PagedApiRequest<CongressCurrentList.CongressCurrentListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/congress/current");
	}
}
