//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Congresses
{
	/// <summary>
	/// Returns a list of congresses and congressional sessions.
	/// </summary>
	public class CongressListRequest : PagedApiRequest<CongressList.CongressListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/congress");
	}
}
