//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Nominations
{
	/// <summary>
	/// Returns the list of printed hearings associated with a specified nomination.
	/// </summary>
	public class NominationHearingsRequest : PagedApiRequest<NominationHearings.NominationHearingsResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 116.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The nomination's assigned number. For example, the value can be 389.
		/// </summary>
		public int NominationNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/nomination/{0}/{1}/hearings", Congress, NominationNumber);
	}
}
