//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CommitteePrints
{
	/// <summary>
	/// Returns the list of texts for a specified committee print.
	/// </summary>
	public class CommitteePrintTextRequest : PagedApiRequest<CommitteePrintText.CommitteePrintTextResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The chamber name. Value can be house, senate, or nochamber.
		/// </summary>
		public Chamber Chamber { get; set; }

		/// <summary>
		/// The jacket number for the print. For example, the value can be 48144.
		/// </summary>
		public int JacketNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee-print/{0}/{1}/{2}/text", Congress, Chamber, JacketNumber);
	}
}
