//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CommitteePrints
{
	/// <summary>
	/// Returns detailed information for a specified committee print.
	/// </summary>
	public class CommitteePrintDetailRequest : JsonFormatApiRequest<CommitteePrintDetail.CommitteePrintDetailResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The chamber name. Value can be house, senate, or nochamber.
		/// </summary>
		public string Chamber { get; set; }

		/// <summary>
		/// The jacket number for the print. For example, the value can be 48144.
		/// </summary>
		public int JacketNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee-print/{0}/{1}/{2}", Congress, Chamber, JacketNumber);
	}
}
