//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.CommitteeMeetings
{
	/// <summary>
	/// Returns a list of committee meetings filtered by the specified congress.
	/// </summary>
	public class CommitteeMeetingCongressRequest : PagedApiRequest<CommitteeMeetingCongress.CommitteeMeetingCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 118.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee-meeting/{0}", Congress);
	}
}
