//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Hearings
{
	/// <summary>
	/// Returns a list of hearings filtered by the specified congress.
	/// </summary>
	public class HearingListByCongressRequest : PagedApiRequest<HearingListByCongress.HearingListByCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 116.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/hearing/{0}", Congress);
	}
}
