//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Nominations
{
	/// <summary>
	/// Returns a list of nominations filtered by the specified congress and sorted by date received from the President.
	/// </summary>
	public class NominationListByCongressRequest : DateRangeApiRequest<NominationListByCongress.NominationListByCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/nomination/{0}", Congress);
	}
}
