//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Nominations
{
	/// <summary>
	/// Returns the list of actions on a specified nomination.
	/// </summary>
	public class NominationActionsRequest : PagedApiRequest<NominationActions.NominationActionsResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The nomination's assigned number. For example, the value can be 2467.
		/// </summary>
		public int NominationNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/nomination/{0}/{1}/actions", Congress, NominationNumber);
	}
}
