//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Nominations
{
	/// <summary>
	/// Returns the list nominees for a position within the nomination.
	/// </summary>
	public class NomineesRequest : PagedApiRequest<Nominees.NomineesResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The nomination's assigned number. For example, the value can be 2467.
		/// </summary>
		public int NominationNumber { get; set; }

		/// <summary>
		/// The ordinal number. For example, the value can be 1.
		/// </summary>
		public int Ordinal { get; set; }

		public override CongressApiEndpoint Endpoint => new("/nomination/{0}/{1}/{2}", Congress, NominationNumber, Ordinal);
	}
}
