//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns a list of congressional committees filtered by the specified chamber.
	/// </summary>
	public class CommitteeListByChamberRequest : DateRangeApiRequest<CommitteeListByChamber.CommitteeListByChamberResponse>
	{
		/// <summary>
		/// The chamber name. Value can be house, senate, or joint.
		/// </summary>
		public string Chamber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}", Chamber);
	}
}
