//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns detailed information for a specified congressional committee.
	/// </summary>
	public class CommitteeDetailsRequest : JsonFormatApiRequest<CommitteeDetails.CommitteeDetailsResponse>
	{
		/// <summary>
		/// The chamber name. Value can be house, senate, or joint.
		/// </summary>
		public string Chamber { get; set; }

		/// <summary>
		/// The committee code for the committee. For example, the value can be hspw00.
		/// </summary>
		public string CommitteeCode { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}/{1}", Chamber, CommitteeCode);
	}
}
