//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns the list of Senate communications associated with a specified congressional committee.
	/// </summary>
	public class SenateCommunicationsByCommitteeRequest : PagedApiRequest<SenateCommunicationsByCommittee.SenateCommunicationsByCommitteeResponse>
	{
		/// <summary>
		/// The chamber name. Value will be senate.
		/// </summary>
		public string Chamber { get; set; }

		/// <summary>
		/// The committee code for the committee. For example, the value can be ssas00.
		/// </summary>
		public string CommitteeCode { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}/{1}/senate-communication", Chamber, CommitteeCode);
	}
}
