//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.SenateCommunications
{
	/// <summary>
	/// Returns a list of Senate communications filtered by the specified congress and communication type.
	/// </summary>
	public class SenateCommunicationListRequest : PagedApiRequest<SenateCommunicationList.SenateCommunicationListResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of communication. Value can be ec, pm, or pom.
		/// </summary>
		public string CommunicationType { get; set; }

		public override CongressApiEndpoint Endpoint => new("/senate-communication/{0}/{1}", Congress, CommunicationType);
	}
}
