//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.BoundCongressionalRecords
{
	/// <summary>
	/// Returns a list of bound Congressional Records filtered by the specified year.
	/// </summary>
	public class BoundCongressionalRecordListByYearRequest : PagedApiRequest<BoundCongressionalRecordListByYear.BoundCongressionalRecordListByYearResponse>
	{
		/// <summary>
		/// The specified year of the bound Congressional record, for example 1990.
		/// </summary>
		public string Year { get; set; }

		public override CongressApiEndpoint Endpoint => new("/bound-congressional-record/{0}", Year);
	}
}
