//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.BoundCongressionalRecords
{
	/// <summary>
	/// Returns a list of bound Congressional Records filtered by the specified year, specified month and specified day.
	/// </summary>
	public class BoundCongressionalRecordListByYearAndMonthAndDayRequest : PagedApiRequest<BoundCongressionalRecordListByYearAndMonthAndDay.BoundCongressionalRecordListByYearAndMonthAndDayResponse>
	{
		/// <summary>
		/// The specified year of the bound Congressional record, for example 1990.
		/// </summary>
		public string Year { get; set; }

		/// <summary>
		/// The specified month of the bound Congressional record, for example 4 for April.
		/// </summary>
		public string Month { get; set; }

		/// <summary>
		/// The specified day of the bound Congressional record, for example 18.
		/// </summary>
		public string Day { get; set; }

		public override CongressApiEndpoint Endpoint => new("/bound-congressional-record/{0}/{1}/{2}", Year, Month, Day);
	}
}
