//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.BoundCongressionalRecords
{
	/// <summary>
	/// Returns a list of bound Congressional Records sorted by most recent.
	/// </summary>
	public class BoundCongressionalRecordListRequest : PagedApiRequest<BoundCongressionalRecordList.BoundCongressionalRecordListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/bound-congressional-record");
	}
}
