//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Summaries
{
	/// <summary>
	/// Returns a list of summaries filtered by congress, sorted by date of last update.
	/// </summary>
	public class BillSummariesByCongressRequest : SortableApiRequest<BillSummariesByCongress.BillSummariesByCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/summaries/{0}", Congress);
	}
}
