//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.CommitteePrints
{
	/// <summary>
	/// Returns a list of committee prints.
	/// </summary>
	public class CommitteePrintListRequest : DateRangeApiRequest<CommitteePrintList.CommitteePrintListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/committee-print");
	}
}
