//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Members
{
	/// <summary>
	/// Returns a list of members filtered by state and district.
	/// </summary>
	public class MemberListByStateAndDistrictRequest : JsonFormatApiRequest<MemberListByStateAndDistrict.MemberListByStateAndDistrictResponse>
	{
		/// <summary>
		/// The two letter identifier for the state the member represents. For example, the value can be MI for Michigan.
		/// </summary>
		public string StateCode { get; set; }

		/// <summary>
		/// The district number for the district the member represents. For example, the value can be 10.
		/// </summary>
		public int District { get; set; }

		public override CongressApiEndpoint Endpoint => new("/member/{0}/{1}", StateCode, District);
	}
}
