//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Members
{
	/// <summary>
	/// Returns detailed information for a specified congressional member.
	/// </summary>
	public class MemberDetailsRequest : JsonFormatApiRequest<MemberDetails.MemberDetailsResponse>
	{
		/// <summary>
		/// The bioguide identifier for the congressional member. For example, the value can be L000174.
		/// </summary>
		public string BioguideId { get; set; }

		public override CongressApiEndpoint Endpoint => new("/member/{0}", BioguideId);
	}
}
