//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Bills
{
	/// <summary>
	/// Returns a list of bills filtered by the specified congress and bill type, sorted by date of latest action.
	/// </summary>
	public class BillListByTypeRequest : SortableApiRequest<BillListByType.BillListByTypeResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of bill. Value can be hr, s, hjres, sjres, hconres, sconres, hres, or sres.
		/// </summary>
		public BillType BillType { get; set; }

		public override CongressApiEndpoint Endpoint => new("/bill/{0}/{1}", Congress, BillType);
	}
}
