//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Bills
{
	/// <summary>
	/// Returns the list of amendments to a specified bill.
	/// </summary>
	public class BillAmendmentsRequest : PagedApiRequest<BillAmendments.BillAmendmentsResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of bill. Value can be hr, s, hjres, sjres, hconres, sconres, hres, or sres.
		/// </summary>
		public BillType BillType { get; set; }

		/// <summary>
		/// The bill's assigned number. For example, the value can be 3076.
		/// </summary>
		public int BillNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/bill/{0}/{1}/{2}/amendments", Congress, BillType, BillNumber);
	}
}
