//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Treaties
{
	/// <summary>
	/// Returns a list of treaties for the specified congress, sorted by date of last update.
	/// </summary>
	public class TreatyListByCongressRequest : DateRangeApiRequest<TreatyListByCongress.TreatyListByCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, value can be 117.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/treaty/{0}", Congress);
	}
}
