//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns the list of committee reports associated with a specified congressional committee.
	/// </summary>
	public class CommitteeReportsByCommitteeRequest : DateRangeApiRequest<CommitteeReportsByCommittee.CommitteeReportsByCommitteeResponse>
	{
		/// <summary>
		/// The chamber name. Value can be house, senate, or joint.
		/// </summary>
		public Chamber Chamber { get; set; }

		/// <summary>
		/// The committee code for the committee. For example, the value can be hspw00.
		/// </summary>
		public string CommitteeCode { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}/{1}/reports", Chamber, CommitteeCode);
	}
}
