//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns a list of congressional committees filtered by the specified congress.
	/// </summary>
	public class CommitteeListByCongressRequest : DateRangeApiRequest<CommitteeListByCongress.CommitteeListByCongressResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}", Congress);
	}
}
