//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns a list of committees filtered by the specified congress and chamber.
	/// </summary>
	public class CommitteeListByCongressChamberRequest : DateRangeApiRequest<CommitteeListByCongressChamber.CommitteeListByCongressChamberResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The chamber name. Value can be house, senate, or joint.
		/// </summary>
		public string Chamber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}/{1}", Congress, Chamber);
	}
}
