//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns a list of congressional committees.
	/// </summary>
	public class CommitteeListRequest : DateRangeApiRequest<CommitteeList.CommitteeListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/committee");
	}
}
