//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Committees
{
	/// <summary>
	/// Returns the list of nominations associated with a specified congressional committee.
	/// </summary>
	public class NominationByCommitteeRequest : PagedApiRequest<NominationByCommittee.NominationByCommitteeResponse>
	{
		/// <summary>
		/// The chamber name. Value will be senate.
		/// </summary>
		public Chamber Chamber { get; set; }

		/// <summary>
		/// The committee code for the committee. For example, the value can be ssas00.
		/// </summary>
		public string CommitteeCode { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee/{0}/{1}/nominations", Chamber, CommitteeCode);
	}
}
