//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Congresses
{
	/// <summary>
	/// Returns detailed information for a specified congress.
	/// </summary>
	public class CongressDetailsRequest : JsonFormatApiRequest<CongressDetails.CongressDetailsResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		public override CongressApiEndpoint Endpoint => new("/0/{0}", Congress);
	}
}
