//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Hearings
{
	/// <summary>
	/// Returns a list of hearings filtered by the specified congress and chamber.
	/// </summary>
	public class HearingListByCongressChamberRequest : PagedApiRequest<HearingListByCongressChamber.HearingListByCongressChamberResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 116.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The chamber name. Value can be house, senate, or nochamber.
		/// </summary>
		public string Chamber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/hearing/{0}/{1}", Congress, Chamber);
	}
}
