//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.CommitteeReports
{
	/// <summary>
	/// Returns a list of committee reports.
	/// </summary>
	public class CommitteeReportsRequest : DateRangeApiRequest<CommitteeReports.CommitteeReportsResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/committee-report");
	}
}
