//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Laws
{
	/// <summary>
	/// Returns a law filtered by specified congress, law type (public or private), and law number.
	/// </summary>
	public class LawListByCongressLawTypeAndLawNumberRequest : PagedApiRequest<LawListByCongressLawTypeAndLawNumber.LawListByCongressLawTypeAndLawNumberResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The law type. Values are either 'pub'or 'priv.'
		/// </summary>
		public string LawType { get; set; }

		/// <summary>
		/// The law number.
		/// </summary>
		public int LawNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/law/{0}/{1}/{2}", Congress, LawType, LawNumber);
	}
}
