//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.HouseCommunications
{
	/// <summary>
	/// Returns a list of House communications filtered by the specified congress and communication type.
	/// </summary>
	public class HouseCommunicationListRequest : PagedApiRequest<HouseCommunicationList.HouseCommunicationListResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of communication. Value can be ec, ml, pm, or pt.
		/// </summary>
		public CommunicationType CommunicationType { get; set; }

		public override CongressApiEndpoint Endpoint => new("/house-communication/{0}/{1}", Congress, CommunicationType);
	}
}
