//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.HouseCommunications
{
	/// <summary>
	/// Returns detailed information for a specified House communication.
	/// </summary>
	public class HouseCommunicationDetailRequest : JsonFormatApiRequest<HouseCommunicationDetail.HouseCommunicationDetailResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 117.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of communication. Value can be ec, ml, pm, or pt.
		/// </summary>
		public CommunicationType CommunicationType { get; set; }

		/// <summary>
		/// The communication's assigned number. For example, the value can be 3324.
		/// </summary>
		public int CommunicationNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/house-communication/{0}/{1}/{2}", Congress, CommunicationType, CommunicationNumber);
	}
}
