//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CommitteeMeetings
{
	/// <summary>
	/// Returns detailed information for a specified committee meeting.
	/// </summary>
	public class CommitteeMeetingDetailRequest : JsonFormatApiRequest<CommitteeMeetingDetail.CommitteeMeetingDetailResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 118.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The chamber name. Value can be house, senate, or nochamber.
		/// </summary>
		public Chamber Chamber { get; set; }

		/// <summary>
		/// The event identifier. For example, the value can be 115538.
		/// </summary>
		public string EventId { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee-meeting/{0}/{1}/{2}", Congress, Chamber, EventId);
	}
}
