//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CommitteeMeetings
{
	/// <summary>
	/// Returns a list of committee meetings.
	/// </summary>
	public class CommitteeMeetingListRequest : PagedApiRequest<CommitteeMeetingList.CommitteeMeetingListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/committee-meeting");
	}
}
