//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.CommitteeReports
{
	/// <summary>
	/// Returns the list of texts for a specified committee report.
	/// </summary>
	public class CommitteeReportIdTextRequest : PagedApiRequest<CommitteeReportIdText.CommitteeReportIdTextResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 116.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The type of committee report. Value can be hrpt, srpt, or erpt.
		/// </summary>
		public ReportType ReportType { get; set; }

		/// <summary>
		/// The committee report's assigned number. For example, the value can be 617.
		/// </summary>
		public int ReportNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/committee-report/{0}/{1}/{2}/text", Congress, ReportType, ReportNumber);
	}
}
