//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.HouseRequirements
{
	/// <summary>
	/// Returns a list of House requirements.
	/// </summary>
	public class HouseRequirementRequest : PagedApiRequest<HouseRequirement.HouseRequirementResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/house-requirement");
	}
}
