//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.Summaries
{
	/// <summary>
	/// Returns a list of summaries sorted by date of last update.
	/// </summary>
	public class BillSummariesAllRequest : SortableApiRequest<BillSummariesAll.BillSummariesAllResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/summaries");
	}
}
