//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Treaties
{
	/// <summary>
	/// Returns the list of committees associated with a specified treaty.
	/// </summary>
	public class TreatyCommitteeRequest : PagedApiRequest<TreatyCommittee.TreatyCommitteeResponse>
	{
		/// <summary>
		/// The congress number. For example, the value can be 116.
		/// </summary>
		public int Congress { get; set; }

		/// <summary>
		/// The treaty's assigned number. For example, the value can be 3.
		/// </summary>
		public int TreatyNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/treaty/{0}/{1}/committees", Congress, TreatyNumber);
	}
}
