//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.Treaties
{
	/// <summary>
	/// Returns a list of treaties sorted by date of last update.
	/// </summary>
	public class TreatyListRequest : DateRangeApiRequest<TreatyList.TreatyListResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/treaty");
	}
}
