//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Enums;
using CapitolSharp.Congress.Models;

namespace CapitolSharp.Congress.DailyCongressionalRecords
{
	/// <summary>
	/// Returns a list of daily Congressional Records filtered by the specified volume number.
	/// </summary>
	public class DailyCongressionalRecordListByVolumeRequest : PagedApiRequest<DailyCongressionalRecordListByVolume.DailyCongressionalRecordListByVolumeResponse>
	{
		/// <summary>
		/// The specified volume of the daily Congressional record, for example 166.
		/// </summary>
		public string VolumeNumber { get; set; }

		public override CongressApiEndpoint Endpoint => new("/daily-congressional-record/{0}", VolumeNumber);
	}
}
