//----------------------
// <auto-generated>
//     Generated using ApiContractor
// </auto-generated>
//----------------------
using System;
using CapitolSharp.Congress.Core.Enums;
using CapitolSharp.Congress.Core.Models;

namespace CapitolSharp.Congress.SenateCommunications
{
	/// <summary>
	/// Returns a list of Senate communications.
	/// </summary>
	public class SenateCommunicationRequest : PagedApiRequest<SenateCommunication.SenateCommunicationResponse>
	{
		public override CongressApiEndpoint Endpoint => new("/senate-communication");
	}
}
